/**
 * Entirely generated by Warp. Keeping for reference.
 * Do not edit manually.
 */

/**
 * Vietnamese Letter Learning Progression for TypeTelex
 * 
 * Based on character frequency analysis and n-gram synergy patterns,
 * this progression introduces letters in an order that maximizes:
 * 1. High-frequency letters first
 * 2. Strong bigram/trigram combinations
 * 3. Natural Vietnamese word formation
 * 4. Non-tonal letters before tonal variants
 */

interface LetterLevel {
  level: number;
  name: string;
  description: string;
  characters: string[];
  newCharacters: string[]; // Only the new letters introduced at this level
  cumulativeCharacters: string[]; // All characters available up to this level
  keyWords: string[]; // Example words that can be formed
  reasoning: string;
}

const vietnameseLetterProgression: LetterLevel[] = [
  {
    level: 1,
    name: "Foundation Letters",
    description: "Core high-frequency letters with strong synergy",
    characters: [' ', 'n', 'h', 'a'],
    newCharacters: ['n', 'h', 'a'],
    cumulativeCharacters: [' ', 'n', 'h', 'a'],
    keyWords: ['an', 'ha', 'nha'],
    reasoning: "n (11.2%), h (9.2%), a (3.8%) - Strong n→h bigram (20.3%), enables basic words"
  },
  
  {
    level: 2,
    name: "Core Consonants",
    description: "Essential consonants for Vietnamese structure",
    characters: [' ', 'n', 'h', 'a', 't', 'c'],
    newCharacters: ['t', 'c'],
    cumulativeCharacters: [' ', 'n', 'h', 'a', 't', 'c'],
    keyWords: ['chat', 'than', 'cat', 'can', 'hat'],
    reasoning: "t (6.7%), c (6.4%) - Common word beginnings ' t' (16.4%), ' c' (15.9%), enables th→, ch→ patterns"
  },

  {
    level: 3,
    name: "High-Frequency Core",
    description: "Most common letters completing basic vocabulary",
    characters: [' ', 'n', 'h', 'a', 't', 'c', 'i', 'g'],
    newCharacters: ['i', 'g'],
    cumulativeCharacters: [' ', 'n', 'h', 'a', 't', 'c', 'i', 'g'],
    keyWords: ['ngi', 'thing', 'cang', 'hang', 'tai'],
    reasoning: "i (6.5%), g (5.6%) - Critical n→g bigram (41%), enables 'ng' ending pattern, common 'i ' word endings"
  },

  {
    level: 4,
    name: "Essential Vowels & Consonants", 
    description: "Key letters for word formation",
    characters: [' ', 'n', 'h', 'a', 't', 'c', 'i', 'g', 'm', 'u', 'y'],
    newCharacters: ['m', 'u', 'y'],
    cumulativeCharacters: [' ', 'n', 'h', 'a', 't', 'c', 'i', 'g', 'm', 'u', 'y'],
    keyWords: ['may', 'hay', 'mau', 'chung', 'thing'],
    reasoning: "m (2.6%), u (2.4%), y (2.1%) - Common endings 'y ' (13.3%), 'm' for plurals, 'u' for common words"
  },

  {
    level: 5,
    name: "Common Extensions",
    description: "Frequent letters expanding vocabulary",
    characters: [' ', 'n', 'h', 'a', 't', 'c', 'i', 'g', 'm', 'u', 'y', 'l', 'o', 'đ'],
    newCharacters: ['l', 'o', 'đ'],
    cumulativeCharacters: [' ', 'n', 'h', 'a', 't', 'c', 'i', 'g', 'm', 'u', 'y', 'l', 'o', 'đ'],
    keyWords: ['lam', 'long', 'doi', 'may', 'chung'],
    reasoning: "l (1.9%), o (1.9%), đ (3.2%) - Common word beginnings ' đ' (10.2%), ' l' (5.9%), core vocabulary"
  },

  {
    level: 6,
    name: "Extended Consonants",
    description: "Additional common consonants",
    characters: [' ', 'n', 'h', 'a', 't', 'c', 'i', 'g', 'm', 'u', 'y', 'l', 'o', 'đ', 'k', 'v', 'r', 'b'],
    newCharacters: ['k', 'v', 'r', 'b'],
    cumulativeCharacters: [' ', 'n', 'h', 'a', 't', 'c', 'i', 'g', 'm', 'u', 'y', 'l', 'o', 'đ', 'k', 'v', 'r', 'b'],
    keyWords: ['khong', 'vao', 'roi', 'bao'],
    reasoning: "k (1.6%), v (1.4%), r (1.4%), b (1.3%) - Word beginnings ' k' (4.9%), ' v' (4.6%), ' b' (4.2%)"
  },

  {
    level: 7,
    name: "Complete Base Alphabet",
    description: "All non-tonal Vietnamese letters",
    characters: [' ', 'n', 'h', 'a', 't', 'c', 'i', 'g', 'm', 'u', 'y', 'l', 'o', 'đ', 'k', 'v', 'r', 'b', 's', 'p', 'e', 'd', 'q', 'x'],
    newCharacters: ['s', 'p', 'e', 'd', 'q', 'x'],
    cumulativeCharacters: [' ', 'n', 'h', 'a', 't', 'c', 'i', 'g', 'm', 'u', 'y', 'l', 'o', 'đ', 'k', 'v', 'r', 'b', 's', 'p', 'e', 'd', 'q', 'x'],
    keyWords: ['song', 'phao', 'den', 'que', 'xem'],
    reasoning: "Completing base alphabet: s (1.2%), p (0.9%), e (0.6%), d (0.4%), q (0.3%), x (0.3%)"
  },

  {
    level: 8,
    name: "Basic Diacritics - No Tones",
    description: "Introduce basic diacritical marks without tone marks",
    characters: [' ', 'n', 'h', 'a', 't', 'c', 'i', 'g', 'm', 'u', 'y', 'l', 'o', 'đ', 'k', 'v', 'r', 'b', 's', 'p', 'e', 'd', 'q', 'x', 'ô', 'ư', 'â', 'ê', 'ơ', 'ă'],
    newCharacters: ['ô', 'ư', 'â', 'ê', 'ơ', 'ă'],
    cumulativeCharacters: [' ', 'n', 'h', 'a', 't', 'c', 'i', 'g', 'm', 'u', 'y', 'l', 'o', 'đ', 'k', 'v', 'r', 'b', 's', 'p', 'e', 'd', 'q', 'x', 'ô', 'ư', 'ê', 'â', 'ơ', 'ă'],
    keyWords: ['môn', 'ưa', 'ân', 'ên', 'ăn'],
    reasoning: "Base vowel modifications: ô (2.6%), ư (1.5%), â (0.8%), ê (0.6%), ơ (0.4%), ă (0.1%)"
  },

  {
    level: 9,
    name: "Common Tone Marks - Acute & Grave",
    description: "Introduce most common tone marks",
    characters: [' ', 'n', 'h', 'a', 't', 'c', 'i', 'g', 'm', 'u', 'y', 'l', 'o', 'đ', 'k', 'v', 'r', 'b', 's', 'p', 'e', 'd', 'q', 'x', 'ô', 'ư', 'â', 'ê', 'ơ', 'ă', 'à', 'ó', 'á', 'ế', 'ớ', 'ầ', 'ằ'],
    newCharacters: ['à', 'ó', 'á', 'ế', 'ớ', 'ầ', 'ằ'],
    cumulativeCharacters: [' ', 'n', 'h', 'a', 't', 'c', 'i', 'g', 'm', 'u', 'y', 'l', 'o', 'đ', 'k', 'v', 'r', 'b', 's', 'p', 'e', 'd', 'q', 'x', 'ô', 'ư', 'â', 'ê', 'ơ', 'ă', 'à', 'ó', 'á', 'ế', 'ớ', 'ầ', 'ằ'],
    keyWords: ['mà', 'có', 'đá', 'kế', 'mớ'],
    reasoning: "High frequency tones: à (2.4%), ó (1.4%), á (1.0%), ế (1.1%), common in everyday words"
  },

  {
    level: 10,
    name: "All Tone Marks",
    description: "Complete Vietnamese character set with all tones",
    characters: [' ', 'n', 'h', 'a', 't', 'c', 'i', 'g', 'm', 'u', 'y', 'l', 'o', 'đ', 'k', 'v', 'r', 'b', 's', 'p', 'e', 'd', 'q', 'x', 
                 'ô', 'ư', 'â', 'ê', 'ơ', 'ă',
                 'à', 'ó', 'á', 'ế', 'ớ', 'ầ', 'ằ',
                 'ấ', 'ờ', 'ậ', 'ủ', 'ợ', 'ộ', 'ể', 'ạ', 'ã', 'ọ', 'ồ', 'ẽ', 'ề', 'ắ', 'ú', 'ứ', 'ữ', 'í', 'ừ', 'ự', 'ò', 'ụ', 'ĩ', 'ổ', 'ỏ', 'ù', 'ỉ', 'ặ', 'ở', 'ũ', 'ẹ', 'é', 'ỗ', 'ử', 'ẫ', 'ẻ', 'ẩ', 'ễ', 'ỡ', 'õ', 'ẳ', 'ý', 'è', 'ỷ', 'ẵ', 'ỳ', 'ỹ'],
    newCharacters: ['ấ', 'ờ', 'ậ', 'ủ', 'ợ', 'ộ', 'ể', 'ạ', 'ã', 'ọ', 'ồ', 'ẽ', 'ề', 'ắ', 'ú', 'ứ', 'ữ', 'í', 'ừ', 'ự', 'ò', 'ụ', 'ĩ', 'ổ', 'ỏ', 'ù', 'ỉ', 'ặ', 'ở', 'ũ', 'ẹ', 'é', 'ỗ', 'ử', 'ẫ', 'ẻ', 'ẩ', 'ễ', 'ỡ', 'õ', 'ẳ', 'ý', 'è', 'ỷ', 'ẵ', 'ỳ', 'ỹ'],
    cumulativeCharacters: [], // Will be populated by getAllCharacters()
    keyWords: ['tất', 'cả', 'từ', 'tiếng', 'việt'],
    reasoning: "Complete Vietnamese orthography with all tone marks and diacritics for full fluency"
  }
];

// Populate the final level's cumulative characters
vietnameseLetterProgression[9].cumulativeCharacters = [
  ...vietnameseLetterProgression[8].cumulativeCharacters,
  ...vietnameseLetterProgression[9].newCharacters
];

/**
 * Get all characters available up to a specific level
 */
function getCharactersForLevel(level: number): string[] {
  if (level < 1 || level > vietnameseLetterProgression.length) {
    return [];
  }
  return [...vietnameseLetterProgression[level - 1].cumulativeCharacters];
}

/**
 * Get all characters as a Set for a specific level (useful for text generation)
 */
function getCharacterSetForLevel(level: number): Set<string> {
  return new Set(getCharactersForLevel(level));
}

/**
 * Get level information
 */
function getLevelInfo(level: number): LetterLevel | null {
  if (level < 1 || level > vietnameseLetterProgression.length) {
    return null;
  }
  return vietnameseLetterProgression[level - 1];
}

/**
 * Get the maximum number of levels available
 */
function getMaxLevel(): number {
  return vietnameseLetterProgression.length;
}

/**
 * Get a readable summary of the progression
 */
function getProgressionSummary(): string {
  return vietnameseLetterProgression
    .map(level => `Level ${level.level}: ${level.name} (${level.newCharacters.length} new chars)`)
    .join('\n');
}

export const letterProgression = [
  ' ', 'n', 'h', 'a', 't', 'c', 'i', 'g', 'm', 'u', 'y', 'l',
  'o', 'd', 'k', 'v', 'r', 'b', 's', 'p', 'e', 'q', 'x',

  // Letters with diacritics from double letter sequence
  ['ô', 'â', 'ê', 'đ'],

  // Vowels with diacrities from `_w` sequence
  ['ư', 'ơ', 'ă'],

  // Dấu sắc (rising tone) - acute accent (´)
  ['á', 'ắ', 'ấ', 'é', 'ế', 'í', 'ó', 'ố', 'ớ', 'ú', 'ứ', 'ý'],
  
  // Dấu huyền (falling tone) - grave accent (`)
  ['à', 'ằ', 'ầ', 'è', 'ề', 'ì', 'ò', 'ồ', 'ờ', 'ù', 'ừ', 'ỳ'],
  
  // Dấu hỏi (question tone) - hook above (?)
  ['ả', 'ẳ', 'ẩ', 'ẻ', 'ể', 'ỉ', 'ỏ', 'ổ', 'ở', 'ủ', 'ử', 'ỷ'],
  
  // Dấu ngã (broken tone) - tilde (~)
  ['ã', 'ẵ', 'ẫ', 'ẽ', 'ễ', 'ĩ', 'õ', 'ỗ', 'ỡ', 'ũ', 'ữ', 'ỹ'],
  
  // Dấu nặng (heavy tone) - dot below (.)
  ['ạ', 'ặ', 'ậ', 'ẹ', 'ệ', 'ị', 'ọ', 'ộ', 'ợ', 'ụ', 'ự', 'ỵ']
]